apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-api-production
  namespace: production
  labels:
    app: iris-api
    environment: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: iris-api
      environment: production
  template:
    metadata:
      labels:
        app: iris-api
        environment: production
    spec:
      containers:
      - name: iris-api
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 8200
        env:
        - name: ENVIRONMENT
          value: "production"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8200
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8200
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      imagePullSecrets:
      - name: gcp-artifact-registry-secret 