apiVersion: v1
kind: Service
metadata:
  name: iris-api-production
  namespace: production
  labels:
    app: iris-api
    environment: production
spec:
  type: LoadBalancer
  ports:
  - port: 8200
    targetPort: 8200
    protocol: TCP
    name: http
  selector:
    app: iris-api
    environment: production 