name: Production Deployment Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  ENVIRONMENT: production
  REGION: asia-south2
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  ARTIFACT_REGISTRY: ${{ secrets.GCP_ARTIFACT_REGISTRY }}-prd

jobs:
  build-test-deploy-prd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Install gke-gcloud-auth-plugin
        run: |
          # Download and install gke-gcloud-auth-plugin
          curl -O https://storage.googleapis.com/gke-gcloud-auth-plugin/v1.0.0/gke-gcloud-auth-plugin-linux-amd64
          chmod +x gke-gcloud-auth-plugin-linux-amd64
          sudo mv gke-gcloud-auth-plugin-linux-amd64 /usr/local/bin/gke-gcloud-auth-plugin
          echo "USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |-
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY }}/iris-api:${{ github.sha }} .
          docker tag ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY }}/iris-api:${{ github.sha }} ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY }}/iris-api:latest
          echo "IMAGE_NAME=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY }}/iris-api:${{ github.sha }}" >> $GITHUB_ENV
          echo "VERSION=${{ github.sha }}" >> $GITHUB_ENV

      - name: Test Docker container
        run: |
          # Start container in background
          docker run -d -p 8200:8200 --name test-container $IMAGE_NAME
          
          # Install requests library for testing
          pip install requests
          
          # Run Python tests
          python test.py
          
          # Cleanup
          docker stop test-container
          docker rm test-container

      - name: Push Docker Image
        run: |-
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY }}/iris-api:${{ github.sha }}
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY }}/iris-api:latest

      - name: Update Kubernetes Deployment
        run: |
          gcloud container clusters get-credentials test-iris-v1 --region=${{ env.REGION }} --project=${{ env.PROJECT_ID }}
          kubectl set image deployment/iris-api iris-api=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY }}/iris-api:${{ github.sha }} -n iris-classifier
          kubectl rollout status deployment/iris-api -n iris-classifier --timeout=300s

      - name: Notify success
        if: success()
        run: |
          echo "🚀 Successfully built, tested, and pushed image to Production Artifact Registry"
          echo "Image: $IMAGE_NAME"
          echo "Version: $VERSION"
          echo "Your GKE production workload will automatically pick up the new image!"

 