apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-api-staging
  namespace: staging
  labels:
    app: iris-api
    environment: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iris-api
      environment: staging
  template:
    metadata:
      labels:
        app: iris-api
        environment: staging
    spec:
      containers:
      - name: iris-api
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 8200
        env:
        - name: ENVIRONMENT
          value: "staging"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8200
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8200
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: gcp-artifact-registry-secret 